version: '3.7'

services:

  node1:
    image: bitnami/etcd:3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=node1 
      - ETCD_ADVERTISE_CLIENT_URLS=http://${NODE1}:2379 
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://${NODE1}:2380 
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379 
      - ETCD_LISTEN_PEER_URLS=http://${NODE1}:2380 
      - ETCD_INITIAL_CLUSTER=node1=http://${NODE1}:2380,node2=http://${NODE2}:2380,node3=http://${NODE3}:2380
    networks:
      etcd:
        ipv4_address: 172.16.28.21

  node2:
    image: bitnami/etcd:3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=node2
      - ETCD_ADVERTISE_CLIENT_URLS=http://${NODE2}:2379 
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://${NODE2}:2380 
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379 
      - ETCD_LISTEN_PEER_URLS=http://${NODE2}:2380 
      - ETCD_INITIAL_CLUSTER=node1=http://${NODE1}:2380,node2=http://${NODE2}:2380,node3=http://${NODE3}:2380


    networks:
      etcd:
        ipv4_address: 172.16.28.22

  node3:
    image: bitnami/etcd:3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=node3
      - ETCD_ADVERTISE_CLIENT_URLS=http://${NODE3}:2379 
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://${NODE3}:2380 
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379 
      - ETCD_LISTEN_PEER_URLS=http://${NODE3}:2380 
      - ETCD_INITIAL_CLUSTER=node1=http://${NODE1}:2380,node2=http://${NODE2}:2380,node3=http://${NODE3}:2380

    networks:
      etcd:
        ipv4_address: 172.16.28.23

networks:
  etcd:
    driver: bridge
    ipam:
      config:
        - subnet:  172.16.0.0/16